# Yarn Berry configuration for monorepo with CI/CD and Docker

# Global cache shared across projects
enableGlobalCache: true

# Use Plug'n'Play for fast and reliable installs without node_modules
nodeLinker: node-modules

# Use 'loose' mode for better compatibility with tools like Storybook
pnpMode: loose

# Disable compression for slightly faster installs
compressionLevel: 0

# Allow yarn.lock to be modified by 'yarn install'
enableImmutableInstalls: false

# Lock the Yarn version for this project to ensure consistency
yarnPath: .yarn/releases/yarn-4.9.2.cjs
