# Yarn Berry configuration for monorepo with CI/CD and Docker

# Global cache shared across projects
enableGlobalCache: true

# Node modules installation mode: use hardlinks to save space
nmMode: 'hardlinks-global'

# Use Plug'n'Play to avoid node_modules, faster installs
nodeLinker: 'pnp'

# PnP strictness: loose is safer for external packages
pnpMode: 'loose'

# No compression for faster installs (can enable if you want smaller cache size)
compressionLevel: 0

# Ensure reproducible installs, lockfile changes blocked
enableImmutableInstalls: true

# Optional: specify Yarn version if you want to lock it
yarnPath: .yarn/releases/yarn-4.9.2.cjs
