/**
 * @file StyleService.js
 * @description Builds inline CSS string for resume PDF template.
 *              Calls resumeStyles.js functions with user customization.
 *              Output replaces {{inlineStyles}} in resume-template.html.
 * @module modules/pdf/services/StyleService
 * @author Nozibul Islam
 */

'use strict';

const {
  getNameStyle,
  getSectionHeadingStyle,
  getBodyStyle,
  getHeaderStyle,
  getAlignmentStyle,
} = require('../../../shared/utils/resumeStyles');

// ==========================================
// CONSTANTS
// ==========================================

// Fixed font size for PDF — replaces useAutoFontSize hook
// A4 is fixed size, no dynamic scaling needed
const PDF_FONT_SIZE = 10.5;
const PDF_LINE_HEIGHT = '1.3';

// ==========================================
// HELPERS
// ==========================================

/**
 * Convert a style object to CSS property string
 * e.g. { fontFamily: 'Arial', fontWeight: 'bold' }
 *   →  "font-family:Arial;font-weight:bold;"
 *
 * @param {Object} styleObj
 * @returns {string}
 */
const styleObjToCSS = (styleObj) => {
  if (!styleObj || typeof styleObj !== 'object') return '';

  return Object.entries(styleObj)
    .filter(
      ([, value]) => value !== undefined && value !== null && value !== ''
    )
    .map(([key, value]) => {
      // Convert camelCase → kebab-case
      const cssKey = key.replace(
        /([A-Z])/g,
        (match) => `-${match.toLowerCase()}`
      );
      return `${cssKey}:${value}`;
    })
    .join(';');
};

/**
 * Convert justifyContent value → text-align equivalent
 * getAlignmentStyle returns { justifyContent: 'center' | 'flex-start' | 'flex-end' }
 * For PDF flex containers, we also need display:flex
 *
 * @param {Object} alignStyle - { justifyContent: string }
 * @returns {string} CSS string
 */
const alignStyleToCSS = (alignStyle) => {
  if (!alignStyle?.justifyContent)
    return `display:flex;justify-content:${alignStyle.justifyContent};flex-wrap:wrap;gap:12px;`;
};

// ==========================================
// MAIN EXPORT
// ==========================================

/**
 * Build inline <style> block from user customization.
 * Uses resumeStyles.js pure functions — same as frontend.
 *
 * @param {Object} customization - User's customization object from Redux/DB
 * @returns {string} Full <style>...</style> block for template injection
 */
exports.buildInlineStyles = (customization) => {
  // customization can be undefined — resumeStyles.js handles defaults
  const safeCustomization =
    customization && typeof customization === 'object'
      ? customization
      : undefined;

  // Call resumeStyles.js functions — exactly like frontend does
  const bodyStyle = getBodyStyle(
    safeCustomization,
    PDF_FONT_SIZE,
    PDF_LINE_HEIGHT
  );
  const nameStyle = getNameStyle(safeCustomization);
  const sectionStyle = getSectionHeadingStyle(safeCustomization);
  const headerStyle = getHeaderStyle(safeCustomization);
  const alignStyle = getAlignmentStyle(safeCustomization?.nameStyle?.position);

  // Convert style objects to CSS strings
  const bodyCSS = styleObjToCSS(bodyStyle);
  const nameCSS = styleObjToCSS(nameStyle);
  const sectionCSS = styleObjToCSS(sectionStyle);
  const headerCSS = styleObjToCSS(headerStyle);
  const alignCSS = alignStyleToCSS(alignStyle);

  return `<style>
  /*
   * Dynamic resume styles — generated by StyleService.js
   * Source: resumeStyles.js (shared with frontend)
   * Font size: ${PDF_FONT_SIZE}pt (fixed for A4 PDF)
   */

  /* Body — font, size, line-height, italic */
  .resume-body { ${bodyCSS}; }

  /* Header block — text-align from nameStyle.position */
  .resume-header { ${headerCSS}; }

  /* Name — font, weight, case, alignment, letter-spacing */
  .resume-name { ${nameCSS}; }

  /* Contact/social flex containers — justify-content from nameStyle.position */
  .resume-header-flex { ${alignCSS}; flex-wrap:wrap; gap:8px; }

  /* Section headings — font, case, weight, border, alignment */
  .resume-section-h2 { ${sectionCSS}; }
</style>`;
};
