// /data/resumeData.js - Simplified Format

export const resumeTemplate = [
  {
    id: '1',
    color: 'blue',
    category: 'ats-friendly',
    features: ['ATS Friendly', 'Clean Design', 'Professional'],
    template: '/assets/resume-templates/template_01.png',
  },
  {
    id: '2',
    color: 'purple',
    category: 'corporate-resume',
    features: ['Colorful', 'Unique Layout', 'Eye-catching'],
    template: '/assets/resume-templates/template_02.png',
  },
  {
    id: '3',
    color: 'amber',
    category: 'executive-resume',
    features: ['Statement', 'Dynamic', 'Attention-grabbing'],
    template: '/assets/resume-templates/template_03.png',
  },
  {
    id: '4',
    color: 'green',
    category: 'creative-resume',
    features: ['Formal', 'Traditional', 'Corporate'],
    template: '/assets/resume-templates/template_04.png',
  },
  {
    id: '5',
    color: 'orange',
    category: 'it-resume',
    features: ['Simple', 'Elegant', 'Focused'],
    template: '/assets/resume-templates/template_05.png',
  },
  {
    id: '6',
    color: 'blue',
    category: 'ats-friendly',
    features: ['ATS Friendly', 'Clean Design', 'Professional'],
    template: '/assets/resume-templates/template_06.png',
  },
  {
    id: '7',
    color: 'purple',
    category: 'corporate-resume',
    features: ['Colorful', 'Unique Layout', 'Eye-catching'],
    template: '/assets/resume-templates/template_07.png',
  },
  {
    id: '8',
    color: 'amber',
    category: 'executive-resume',
    features: ['Statement', 'Dynamic', 'Attention-grabbing'],
    template: '/assets/resume-templates/template_08.png',
  },
  {
    id: '9',
    color: 'green',
    category: 'creative-resume',
    features: ['Formal', 'Traditional', 'Corporate'],
    template: '/assets/resume-templates/template_09.png',
  },
  {
    id: '10',
    color: 'orange',
    category: 'it-resume',
    features: ['Simple', 'Elegant', 'Focused'],
    template: '/assets/resume-templates/template_10.png',
  },
  {
    id: '11',
    color: 'blue',
    category: 'ats-friendly',
    features: ['ATS Friendly', 'Clean Design', 'Professional'],
    template: '/assets/resume-templates/template_11.png',
  },
  {
    id: '12',
    color: 'purple',
    category: 'corporate-resume',
    features: ['Colorful', 'Unique Layout', 'Eye-catching'],
    template: '/assets/resume-templates/template_12.png',
  },
  {
    id: '13',
    color: 'amber',
    category: 'executive-resume',
    features: ['Statement', 'Dynamic', 'Attention-grabbing'],
    template: '/assets/resume-templates/template_13.png',
  },
  {
    id: '14',
    color: 'green',
    category: 'creative-resume',
    features: ['Formal', 'Traditional', 'Corporate'],
    template: '/assets/resume-templates/template_14.png',
  },
  {
    id: '15',
    color: 'green',
    category: 'creative-resume',
    features: ['Formal', 'Traditional', 'Corporate'],
    template: '/assets/resume-templates/template_14.png',
  },
  {
    id: '16',
    color: 'green',
    category: 'creative-resume',
    features: ['Formal', 'Traditional', 'Corporate'],
    template: '/assets/resume-templates/template_14.png',
  },
];
